import configpaser
import subprocess


def parse_plink_conf(config_file: str):
    """Parse the plink config file.

    Key arguments:
    --------------
    config_file: str
        path to plink config file

    Returns:
    --------

    """
    config = configparser.ConfigParser()
    config.read(config_file)
    plink_path = config['PATHS']['plink_path']
    return plink_path


def run_plink(bfile: str, *flags: str, make_bed: bool=True, plink_conf: str="../plink.conf"):
    """Run plink binary with flag arguments.

    Key arguments:
    --------------
    bfile: str
        prefix for plink binary files (.bed, .bim, .fam)
    *flags: str
        flags to pass to plink binary file
    make_bed: bool
        determines if binary files are generated by plink command
    plink_path: str
        path to plink executable

    Returns:
    --------

    """
    plink_path = parse_plink_conf(plink_conf)

    if make_bed:
        command = f'{plink_path} --bfile {bfile} --silent --make-bed'
    else:
        command = f'{plink_path} --bfile {bfile} --silent'
    for flag in flags:
        command += f' {flag}'
    subprocess.run(command, text=True, check=True, shell=True)
